#!/usr/bin/env bash

home() {
	home-manager switch --flake .#${USER}@${HOSTNAME}
}

nixos() {
	sudo nixos-rebuild switch --flake .#${HOSTNAME}
}

show_help() {
	echo "Usage: $0 [option]"
	echo
	echo "Options:"
	echo "  h, home           Reload home-manager"
	echo "  n, nixos          Reload nixos"
	echo "  a                 Reload both"
}

case $1 in
	h | home)
		home
		;;
	n | nixos)
		nixos
		;;
	a)
		home
		nixos
		;;
	*)
		show_help
		;;
esac
