# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ll="ls -l --color"
alias grep="grep --color=auto"
alias k="kubectl"

export PATH="$PATH:$HOME/go/bin"
export EDITOR="vi"
export PASSWORD_STORE_DIR="$HOME/github.com/yagoyudi/pass";

source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"

eval "$(starship init bash)"

