" style
colo default

" automatically indent new lines
set autoindent " (alpine)
set smartindent

set smarttab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" use case when searching
set noignorecase

" automatically write files when changing when multiple files open
set autowrite

" turn col and row position on in bottom right
set ruler

" show command and insert mode
set showmode

" disable bell (also disable in .inputrc)
set noerrorbells
set vb t_vb=

" more risky, but cleaner
set nobackup
set noswapfile
set nowritebackup

set icon

" search
set nohlsearch
set incsearch
set linebreak

" avoid most of the 'Hit Enter ...' messages
set shortmess=aoOtTI

" disable bracket matching
set noshowmatch

" wrap around when searching
set wrapscan
set nowrap

" stop complaints about switching buffer with changes
set hidden

" command history
set history=100

if has("syntax")
  syntax enable
endif

" faster scrolling
set ttyfast

" allow sensing the filetype
filetype plugin on

set cinoptions+=:0

" better command-line completion
set wildmenu

" better cursor movement
set virtualedit=all
set wrap

" start at last place you were editing
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" netrw
let g:netrw_banner = 0
let g:netrw_localcopydircmd = 'cp -r'
let g:netrw_keepdir = 0

" make
set makeprg=./compile

set backspace=indent,eol,start

" vim-go
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_functions_parameters = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_diagnostic_errors = 1
let g:go_highlight_diagnostic_warnings = 1

" keybindings
nnoremap ; q:i
noremap <C-n> <C-d>
noremap <C-p> <C-b>
map Y y$
