colo habamax

set nocompatible

syntax enable
filetype indent plugin on


set path+=** " Search down into subfolders.
set wildmenu " Display all matching files when we tab complete.

" NOW WE CAN:
" - Hit tab to :fin by partial match.
" - Use * to make it fuzzy.

" THINGS TO CONSIDER:
" - :b lets you autocomplete any open buffer.



" AUTOCOMPLETE:
" The good stuff is documented in |ins-completion|.

" HIGHLIGHTS:
" - ^x^n for JUST this file.
" - ^x^f for filenames (works with our path trick!).
" - ^x^] for tags only.
" - ^n for anything specified by the 'complete' option.

" NOW WE CAN:
" - Use ^n and ^p to go back and forth in the suggestion list.



" NETRW:
let g:netrw_banner=0        " Disable annoying banner.
let g:netrw_browse_split=4  " Open in prior window.
let g:netrw_altv=1          " Open splits to the right.
let g:netrw_liststyle=3     " Tree view.
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
" Check |netrw-browse-maps| for more mappings.


set makeprg=./compile

" References:
" - https://www.youtube.com/watch?v=XA2WjJbmmoM

